### ISSUE TITLE
UnhandledPromiseRejectionWarning causes ROS to stop installing

### ISSUE THREAD

**Issue by nmerrill67** [betwo/github-setup-catkin#3]
Hello, thanks for this great package! I tried it out today, following the example in the README, and on the action `Run betwo/github-setup-catkin@v1.0.0` in the log it says it's throwing a `UnhandledPromiseRejectionWarning`, and ROS stops installing. After that, it moves on to try and run the `catkin_make_isolated` command and fails with `ImportError: No module named catkin.builder`.  I am assuming clearly that the first "warning" is the issue, since ROS stops installing. 

Here is my c-cpp.yml:
```
name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: [ubuntu-18.04]
    strategy:
      fail-fast: false
      matrix:
        compiler: ["/usr/bin/g++"]
    steps:
    - uses: actions/checkout@v2
    - uses: betwo/github-setup-catkin@v1.0.0
      with:
        ros-version: 'melodic'
        workspace: '$GITHUB_WORKSPACE'
    - run: catkin_make_isolated -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
```

If I am using it wrong, please let me know!
